### ISSUE TITLE
next-auth and nestjs

### ISSUE THREAD

**Issue by cloudcompute** [andrei-picus-tink/kaizen-nestjs#1]
Hi

I went through this code. I have a qs. pl. answer.

Nestjs is running on on port 3001. Is next-auth also running in the same (Nest) process.. what configuration do I need to do to accomplish this? The thing that is confusing is next-auth functionality is used in both the backend and frontend. What magic did you do that both are able to share the "same" next-auth? 

If possible, pl. explain in detail.

Thanks

**Comment by NiGhTTraX** [comment]
Hey @ramandhingra

> Is next-auth also running in the same (Nest) process

No, they are separate processes.

> What magic did you do that both are able to share the "same" next-auth?

[Requests from the frontend](https://github.com/andrei-picus-tink/kaizen-nestjs/blob/b108038772796251ada97cd881ca950804f83785/packages/frontend/src/services/cats.ts#L12-L13) will include the JWT cookie from next-auth that will be [decoded from NestJS](https://github.com/andrei-picus-tink/kaizen-nestjs/blob/b108038772796251ada97cd881ca950804f83785/packages/backend/src/auth.guard.ts#L38) in the auth guard. To avoid cross-origin requests you can set up a proxy in the Next backend e.g. [using rewrites](https://nextjs.org/docs/api-reference/next.config.js/rewrites).

**Comment by cloudcompute** [comment]
@NiGhTTraX 

Thank you for the response. It will certainly help me setting up the next-auth. One more question.. is it possible to accomplish the next-auth along with the Nest using the next-auth's 'sessions' instead of next-auth's 'JWTs'. Both the processes are writing to the same database whose setup is like this ..

https://next-auth.js.org/adapters/prisma#setup

**Comment by NiGhTTraX** [comment]
@ramandhingra haven't tried it, but you should be able to get the session ID from Next and then validate it in Nest, similar to the JWT example in this repo.
